"""add games.created_at

Revision ID: 15cb94411b51
Revises: 1e8011d43bf8
Create Date: 2026-04-04 00:28:34.022411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "15cb94411b51"
down_revision: Union[str, Sequence[str], None] = "1e8011d43bf8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_games_id"), table_name="games")
    op.drop_index(op.f("ix_games_name"), table_name="games")
    op.drop_table("games")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("released_year", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("platform", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("genre", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "allow_multiplayer", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("games_pkey")),
        sa.UniqueConstraint(
            "name",
            "platform",
            name=op.f("uk_name_platform"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_games_name"), "games", ["name"], unique=False)
    op.create_index(op.f("ix_games_id"), "games", ["id"], unique=False)
    # ### end Alembic commands ###
