"""initial

Revision ID: 1e8011d43bf8
Revises: caf2ed4f1c0c
Create Date: 2026-03-23 23:33:03.332706

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1e8011d43bf8"
down_revision: Union[str, Sequence[str], None] = "caf2ed4f1c0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_games_name"), table_name="games")
    op.create_index(op.f("ix_games_name"), "games", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_games_name"), table_name="games")
    op.create_index(op.f("ix_games_name"), "games", ["name"], unique=True)
    # ### end Alembic commands ###
